name: "Changelog Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Ensure changelog has been updated
    runs-on: ubuntu-latest
    steps:
      - name: Verify Changed files
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
        filters: |
          txt:
            - '**/*.txt'
