name: "Changelog Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Ensure a readme.txt file has been updated if a theme has been changed
    runs-on: ubuntu-latest
    steps:
      - name: Verify any readme files
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            theme_change:
              - '**/**'
            theme_readme:
              - '**/readme.txt'
            root_files:
              - '**.**'
              - '!**/**.**'
            excluded_subfolders:
              - 'variations/**'
              - '.github/**'
              - '.husky/**'
              - '.phab/**'
      - name: Logging
        run: | 
          echo "theme_change ${{steps.filter.outputs.theme_change}}"
          echo "excluded_subfolders ${{steps.filter.outputs.excluded_subfolders}}"
          echo "root_files ${{steps.filter.outputs.root_files}}"
          echo "theme_readme ${{steps.filter.outputs.theme_readme}}"
      - name: Reminder to update changelog
        if: ${{ (steps.filter.outputs.excluded_subfolders == 'false' || steps.filter.outputs.root_files == 'false') && steps.filter.outputs.theme_change == 'true' && steps.filter.outputs.theme_readme == 'false' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Please update the changelog in the readme.txt of any updated themes.')