name: "Changelog Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{steps.changefile.outputs.continue}}
    steps:
    - uses: actions/checkout@v1
    - name: Ignore changes to all files in root, and specific subfolders
      id: changefile
      run: |
        changed_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}})
        file_count=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}} | wc -l )
        if [[$changed_file == './*.*' || $changed-file == 'variations/**' || $changed_file == '.github/**' || '.husky/**' || '.phab/**']]
        then
          echo ::set-output name=continue::false
        else
          echo ::set-output name=continue::true
        fi
  main:
    name: Ensure a readme.txt file has been updated
    runs-on: ubuntu-latest
    steps:
      - name: Verify any readme files
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            theme_update:
              - '**/**'
            readme:
              - '**/readme.txt'
      - name: Reminder to update changelog
        if: ${{ steps.filter.outputs.theme_update == 'true' && steps.filter.outputs.readme == 'false' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Please update the changelog in the readme.txt of any updated themes.')