name: "Update Packages"

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  main:
    if: github.event.review.state == 'approved'
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"
          all_commits: true
          all_tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Git Identity
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
      - name: Update Packages
        run: |
          npm ci
          npm run update-versions
          npm run update-stylecss
      - name: Commit style.css Changes
        run: |
          git add . 
          git commit -m "chore:"" auto-update style.css files"
          git push
