name: "Update Packages"

on:
  pull_request_target:
    types: [ closed ]

jobs:
  main:
    if: github.event.pull_request.merged == true
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      
      - run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: npm ci
      - run: npm run update-packages
