name: "Update Packages"

on:
  pull_request_target:
    types: [ closed ]

jobs:
  main:
    if: github.event.pull_request.merged == true
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"
          all_commits: true
          all_tags: true

      - uses: actions/setup-node@v2
        with:
          node-version: 12
      
      - run: git config --global user.email octobot@github.com
      - run: git config --global user.name "GitHub Actions"
      - run: npm ci
      - run: npm run update-packages
