name: "Update Packages"

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  main:
    if: github.event.pull_request.merged == true
    name: Update All Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: "0"
          all_commits: true
          all_tags: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Git Identity
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
      - name: Update Packages
        run: |
          npm ci
          npm run update-packages
      - name: Commit Changes
        run: |
          git add . 
          git commit -m "chore:"" auto-update package info"
          git push
